name: Publish Nlbn-ui-vite To Npm

on:
  push:
    branches: [publish-nlbn-ui]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish npm"

    environment: npm

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
      - name: Install modules
        run: pnpm install
      - name: Build
        run: npm run build
      - name: "Publish to the npm registry"
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/  # 设置发包npm地址仓库
      - run: npm publish # 执行发布
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM}} # 刚刚设置的 NPM_TOKEN